from .yandex_plus      import fetch_yandex_plus
from .vk_combo         import fetch_vk_combo
from .okko             import fetch_okko
from .ivi              import fetch_ivi
from .megogo           import fetch_megogo
from .start            import fetch_start
from .wink             import fetch_wink
from .moretv           import fetch_moretv
from .premier          import fetch_premier
from .kinopoisk        import fetch_kinopoisk
